# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envguard < Formula
  desc "Detect exposed secrets and credentials before they reach AI tools"
  homepage "https://github.com/winky/envguard"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winky/envguard/releases/download/v0.2.3/envguard-darwin-amd64.tar.gz"
      sha256 "770a4f3c02151d2a5e8385fd28264abc0d08e89b2f3109b955954fc567ac0eeb"

      define_method(:install) do
        bin.install "envguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winky/envguard/releases/download/v0.2.3/envguard-darwin-arm64.tar.gz"
      sha256 "042e2313781c0f8b41a1479c8b4bfc63e4f08aa04cdf5015c93e3324961df5b2"

      define_method(:install) do
        bin.install "envguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/winky/envguard/releases/download/v0.2.3/envguard-linux-amd64.tar.gz"
      sha256 "c35ed82306a56851f589095cab6c27b8d9d220b6bfb1b3b310316b0fdf832735"
      define_method(:install) do
        bin.install "envguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winky/envguard/releases/download/v0.2.3/envguard-linux-arm64.tar.gz"
      sha256 "5f8490e79cfc8c56adb65ea19c1d83d0366b5f45230a44484fe8fcd2391d5f7a"
      define_method(:install) do
        bin.install "envguard"
      end
    end
  end

  test do
    system "#{bin}/envguard", "--version"
  end
end
