# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envguard < Formula
  desc "Detect exposed secrets and credentials before they reach AI tools"
  homepage "https://github.com/winky/envguard"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winky/envguard/releases/download/v0.2.1/envguard-darwin-amd64.tar.gz"
      sha256 "06905ba399ed38c0109e500083faf94b566def9e779205084600ef1e602aa021"

      define_method(:install) do
        bin.install "envguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winky/envguard/releases/download/v0.2.1/envguard-darwin-arm64.tar.gz"
      sha256 "e953192c6f3850c9f243852dc8bbe23375b0ba0b1a98d8ac2f4a79036a0d828b"

      define_method(:install) do
        bin.install "envguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/winky/envguard/releases/download/v0.2.1/envguard-linux-amd64.tar.gz"
      sha256 "39222f882474831868297ff2f1e74d9e5446abb37288a06305c6231d8373a1bc"
      define_method(:install) do
        bin.install "envguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winky/envguard/releases/download/v0.2.1/envguard-linux-arm64.tar.gz"
      sha256 "6befa0b5dbd011a580f5dbad6ff8b530fb56922bcbc600e3499548cef9f89f66"
      define_method(:install) do
        bin.install "envguard"
      end
    end
  end

  test do
    system "#{bin}/envguard", "--version"
  end
end
