# This file was generated by GoReleaser. DO NOT EDIT.
cask "envguard" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "a6a922551c83b930ed68b6c354120dcd3c5e57a05731465764b18c40e8b75b3c"
      url "https://github.com/winky/envguard/releases/download/v#{version}/envguard-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "02cb3140d43a3936a7584e63f48c59ff3aef67658aadb0af46fe94db9557a50e"
      url "https://github.com/winky/envguard/releases/download/v#{version}/envguard-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ebc06c2cc319e289f9178508e5eb71b01bce9a395a2fb6858b27dd631d3825ad"
      url "https://github.com/winky/envguard/releases/download/v#{version}/envguard-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "64337e6bd6e04ee2f455aaa620544ccdca0cdd65d0af68a4b48339b71fb5dfb5"
      url "https://github.com/winky/envguard/releases/download/v#{version}/envguard-linux-arm64.tar.gz"
    end
  end

  name "envguard"
  desc "Detect exposed secrets and credentials before they reach AI tools"
  homepage "https://github.com/winky/envguard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envguard"

  # No zap stanza required

end
